name: Hello (Python)
description: Greet someone and expose a greeting output
inputs:
  who-to-greet:
    description: Name to greet
    required: true
    default: World
outputs:
  greeting:
    description: The greeting that was printed
runs:
  using: docker
  # Option A – let GitHub build from Dockerfile each run
  image: Dockerfile
  # Option B – use a pre-built image to avoid rebuilds:
  # image: docker://ghcr.io/your-org/hello-python-action:v1
  args:
    - ${{ inputs.who-to-greet }}
