name: Workflow Iteration (Breakpoint with SSH)

on:
  workflow_dispatch:

jobs:
  fail-with-breakpoint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v5.0.0
      - name: Fail
        run: |
          echo "::error Purposefully failing the job"; exit 1;
      - name: Breakpoint if Failed
        if: failure()
        uses: namespacelabs/breakpoint-action@664d004eae0e89e248fafe14fd5e97d28440a85e # v0.0.13
        with:
          duration: 10m
          authorized-users: sidpalas
